### ISSUE TITLE
[FRONT] Re-organiser le css et les dossiers

### ISSUE THREAD

**Issue by werterhalimi** [42LTeam/pong#10]
C'est le bordel

**Comment by 8L312** [comment]
Sur la branche rmonney ya déjà du ménage de fait mais il faudrait commencer à rendre les components le plus modulable possible pour qu'ils n'en reste que quelques-uns et qu'ont puisse les réutiliser tout le temps

**Comment by 0xlowell** [comment]
Done la derniere fois, maintenant tout est clean sur main
