### ISSUE TITLE
[BACK/FRONT] Taille infinie des responses

### ISSUE THREAD

**Issue by werterhalimi** [42LTeam/pong#12]
Le endpoints pour recuperer les messages d'un channel, par exemples, les renvoies tous ce qui peut causer des crash en front et en back il faudrait faire un systeme de page sur le back pour qu'il les renvoient genre 100 par 100, et coter front il faudrait faire que quand l'utilisateur a scroll les 80 premier message charger faire la requettes pour les 100 suivants

**Comment by werterhalimi** [comment]
> On peut implémenter deux params supplémentaires au request, genre `skip` et `take`.
> 
> 
> 
> `Skip `pour ignore nb de messages.
> 
> `Take` pour fetch nb de messages.
> 
> 
> 
> 
> 
> Ca vous irait ?

Plus simple, on fait un règle pages sur tout les endpoints qui par défaut vaut 1 et les requêtes retourne genre les 100 premier si la page vaut 1 puis du 100 au 200 premiers si la page vaut 2 etc

**Comment by es4nchez** [comment]
Ok ca me va comme ca. Je vais quand même utilise skip et take dans les services, ca sera plus simple et c'est intégré dans prisma pour faire ca !
