### ISSUE TITLE
[BACKFRONT] time to get real online pong

### ISSUE THREAD

**Issue by 8L312** [42LTeam/pong#120]
vazy viens on dit se co en privé à deux sur  même ordi c'est ghetto

**Comment by werterhalimi** [comment]
Hein ?

**Comment by 8L312** [comment]
Apagnan

**Comment by 8L312** [comment]
> Hein ?

Apagnan

**Comment by 8L312** [comment]
C'est pour faire en sorte que notre pong soit jouable entre plusieurs ordis de 42
