### ISSUE TITLE
[FRONT & BACK] Bugs social

### ISSUE THREAD

**Issue by 0xlowell** [42LTeam/pong#124]
https://github.com/42LTeam/pong/assets/93135858/d912f62c-d18e-456f-a7a5-07d692bdf724

**Comment by 0xlowell** [comment]
j'en ai un autre, qui va avec la creation des messages privés, quand on click sur la croix messages privés  et on cree un pm, on a 2 fois la personne et le nom du channel est différent et c'est possible d'avoir un doublon

**Comment by 0xlowell** [comment]
<img width="187" alt="Screenshot 2023-09-03 at 23 04 08" src="https://github.com/42LTeam/pong/assets/93135858/399e465b-43fd-4fac-b8cb-370e5a5f9856">

jmorcom+lzima et lzima sur le compte de jmorcom = sensé etre le meme chan

<img width="1466" alt="Screenshot 2023-09-03 at 23 06 17" src="https://github.com/42LTeam/pong/assets/93135858/494ebb0e-c4c7-4913-b4f6-bd277b2c9d14">

**Comment by es4nchez** [comment]
Les doublons normalement c'est fix, par contre j'ai pas réussi à reproduire la première erreur avec la vidéo, tu l'as toujours ?

**Comment by 0xlowell** [comment]
> 

Hum je vais retest, ca se trouve c'est patch par un autre bail
