### ISSUE TITLE
[BACKFRONT] 2FA probleme

### ISSUE THREAD

**Issue by 8L312** [42LTeam/pong#138]
si on clique sur activer la 2FA mais qu'on fait rien avec le QR, la prochaine fois qu'on doit se connecter on nous demande un code alors que j'ai pas setup la 2FA jusqu'au bout

**Comment by werterhalimi** [comment]
Bah c'est normal si t'active la 2fa tu dois passer par là 2fa pour te log

**Comment by 8L312** [comment]
Ouais mais du coup si t'as jamais setup tu te retrouve cock-block pask'on te demande un code que tu as pas 😢

**Comment by werterhalimi** [comment]
Bah on peut faire une confirmation mais c'est chiant
