### ISSUE TITLE
[FRONT] social URLs protection

### ISSUE THREAD

**Issue by 8L312** [42LTeam/pong#139]
si on rentre l'url des conversations a la mano on tombe sur une page de chat vide plutot que sur une erreur genre : http://localhost:5173/social/666 
Et ya un monde ou si on essaie d'aller sur une conv qui existe mais qu'on est pas censé voir on eut la chopper comme ça aussi btw

**Comment by werterhalimi** [comment]
Tu peux rajouter un catch dans api.ts sur le acios dans le return genre return axios(config).catch(handleErrFunc);
