### ISSUE TITLE
[FRONT] add (dis)connect options

### ISSUE THREAD

**Issue by 8L312** [42LTeam/pong#141]
possibilité de de deco et un page pour se co

**Comment by 8L312** [comment]
@werterhalimi je galere a comprendre je suis censé deconnecter le user aussi bien en back qu'en front

**Comment by werterhalimi** [comment]
Il faut clear les cookies pour délog l'user tu peux le faire que en front

**Comment by 8L312** [comment]
Kay thx je check ça aujo alors

**Comment by 8L312** [comment]
@werterhalimi Wallah j'arrive à R j'essaie de supprimer le cookie il veut pas et en essayant des bails plus sombre ya rien qui passe non plus 🤡
