### ISSUE TITLE
[BACKFRONT] max username length

### ISSUE THREAD

**Issue by 8L312** [42LTeam/pong#143]
Tiens vu que tu sais pas quoi faire on peut limiter les username a une taille max pour eviter des cringeries de ce genre : 
<img width="1077" alt="Screen Shot 2023-09-05 at 11 50 52 PM" src="https://github.com/42LTeam/pong/assets/87899853/0c0f82e6-f800-44c0-98a7-c8b27e673210">

**Comment by es4nchez** [comment]
Done, merci
