### ISSUE TITLE
[BACKFRONT] retourner les erreurs au front

### ISSUE THREAD

**Issue by 8L312** [42LTeam/pong#198]
Avec un flash ou n'importe, ne pas laisser l'user dans le flou

**Comment by 8L312** [comment]
et les logs aussi eventuellement plutôt que de return sans rien dire ni faire

**Comment by 0xlowell** [comment]
git checkout 000-from-ban-kick-mute-notif-setting-up-on-api-ts

**Comment by 0xlowell** [comment]
Merge dans startfresh
