### ISSUE TITLE
[FRONT] Responsive

### ISSUE THREAD

**Issue by werterhalimi** [42LTeam/pong#27]
La plupart des body sont pas vraiment responsive. Le social quand t'es dans un tchat ca va sur l horiyontal mais le reste c'est foireu

**Comment by 8L312** [comment]
<img width="2101" alt="Capture d’écran 2023-09-23 à 11 43 31 PM" src="https://github.com/42LTeam/pong/assets/87899853/735087b9-def0-4932-8fc8-22723e8adca5">

**Comment by 8L312** [comment]
Quand on a un très long message c'est particulièrement cringe

**Comment by 0xlowell** [comment]
Rono est sur le coup
