### ISSUE TITLE
[FRONT] la partie ajouter de friends

### ISSUE THREAD

**Issue by 8L312** [42LTeam/pong#59]
Le comportement est un peu bizarre quand on choisit qqun de la recherche rapide.. possibles résolutions : 
-Remplir le text input avec son nom quand on appuie dessus
-Quand on appuie sur qqun sa bulle change de couleur (genre comme les hovers de certain compos)
-Ajouter directement un petit bouton ajouter sur les bubbles des users

Aussi est-ce qu'on a moyen de pouvoir empêcher l'user de spammer les demandes d'ami à la même personne ?

**Comment by werterhalimi** [comment]
on it
