### ISSUE TITLE
[FRONT BACK] getUsers / getAllUsers

### ISSUE THREAD

**Issue by 8L312** [42LTeam/pong#68]
La nouvelle implémentation est pas si déconnante dans le cadre du social mais j'ai l'impression qu'on peut plus avoir  tous les users en une fois (et j'en ai typiquement besoin pour le leaderboard)

**Comment by werterhalimi** [comment]
normalement c'est bon je te laisse review la PR

**Comment by werterhalimi** [comment]
tu peux utiliser la fonction sans argument maintenant et elle te donne tout les users
