### ISSUE TITLE
[BACK] Reorganiser les controllers

### ISSUE THREAD

**Issue by werterhalimi** [42LTeam/pong#9]
Certains endpoints friend sont dans le controller user entre autres.
Il faudrait avoir un service par table et jamais passer par this.primsa.TABLE en dehors du service de la table.

**Comment by es4nchez** [comment]
Je suis dessus, j'ai réorganisé la plupart, je me pose juste des questions pour le service `getFriendsOfUser,`
qui utilise pour le coup `this.prisma.userFriendship.findMany` et `this.prisma.user.findMany`.
Il a plus de sens d'être dans User ou dans Friend ?

**Comment by werterhalimi** [comment]
bonne question on regarde ca demain
